version: "3.8"

services:
  web:
    build: ./StravaRanking
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./StravaRanking/:/usr/src/StravaRanking/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ranking_app
      - POSTGRES_PASSWORD=ranking_app
      - POSTGRES_DB=ranking_app_dev

volumes:
  postgres_data: